//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoViatic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoViatic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget:.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Trip.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trip was {0} succesfully.
        /// </summary>
        internal static string CreateEditTripConfirm {
            get {
                return ResourceManager.GetString("CreateEditTripConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Create your new Trip.
        /// </summary>
        internal static string CreateTripTittle {
            get {
                return ResourceManager.GetString("CreateTripTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your new Viatic.
        /// </summary>
        internal static string CreateViaticTittle {
            get {
                return ResourceManager.GetString("CreateViaticTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Travel Companion.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edited.
        /// </summary>
        internal static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your Trip.
        /// </summary>
        internal static string EditTripTittle {
            get {
                return ResourceManager.GetString("EditTripTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your Viatic.
        /// </summary>
        internal static string EditViaticTittle {
            get {
                return ResourceManager.GetString("EditViaticTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Day:.
        /// </summary>
        internal static string EndDay {
            get {
                return ResourceManager.GetString("EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Ammount.
        /// </summary>
        internal static string InvoiceAmmount {
            get {
                return ResourceManager.GetString("InvoiceAmmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing this App. You can support the developer by clicking occasionally on advertising..
        /// </summary>
        internal static string LargeMessage {
            get {
                return ResourceManager.GetString("LargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trip.
        /// </summary>
        internal static string NavTittleCreateTripPage {
            get {
                return ResourceManager.GetString("NavTittleCreateTripPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Viatic.
        /// </summary>
        internal static string NavTittleCreateViaticPage {
            get {
                return ResourceManager.GetString("NavTittleCreateViaticPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trip.
        /// </summary>
        internal static string NavTittleEditTripPage {
            get {
                return ResourceManager.GetString("NavTittleEditTripPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Viatic.
        /// </summary>
        internal static string NavTittleEditViaticPage {
            get {
                return ResourceManager.GetString("NavTittleEditViaticPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Trips.
        /// </summary>
        internal static string NavTittleTripsPage {
            get {
                return ResourceManager.GetString("NavTittleTripsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW TRIP.
        /// </summary>
        internal static string NewTrip {
            get {
                return ResourceManager.GetString("NewTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, let&apos;s créate a new Trip.
        /// </summary>
        internal static string NewTripHeader {
            get {
                return ResourceManager.GetString("NewTripHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW VIATIC.
        /// </summary>
        internal static string NewViatic {
            get {
                return ResourceManager.GetString("NewViatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the current trip ?.
        /// </summary>
        internal static string QuestionT {
            get {
                return ResourceManager.GetString("QuestionT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the current viatic ?.
        /// </summary>
        internal static string QuestionV {
            get {
                return ResourceManager.GetString("QuestionV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Day:.
        /// </summary>
        internal static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Message.
        /// </summary>
        internal static string TripEditCreation {
            get {
                return ResourceManager.GetString("TripEditCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viatic.
        /// </summary>
        internal static string Viatic {
            get {
                return ResourceManager.GetString("Viatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viatic Type:.
        /// </summary>
        internal static string ViaticCategory {
            get {
                return ResourceManager.GetString("ViaticCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ViaticDescription {
            get {
                return ResourceManager.GetString("ViaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIATICS: .
        /// </summary>
        internal static string ViaticsD {
            get {
                return ResourceManager.GetString("ViaticsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Profile.
        /// </summary>
        internal static string VisitProfile {
            get {
                return ResourceManager.GetString("VisitProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        internal static string VisitWeb {
            get {
                return ResourceManager.GetString("VisitWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
